[package]
name = "yogurt-utils"
version = "0.1.0"
authors = ["gpi <gpimpale29@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yogurt = {path = ".." }
bumpalo="3.2"
conllu = "*"
